from enum import StrEnum


class AgentMessageType(StrEnum):
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_ACCEPTED = "TASK_ACCEPTED"
    ARTIFACT_CREATED = "ARTIFACT_CREATED"
    CHALLENGE_RAISED = "CHALLENGE_RAISED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    REVISION_COMPLETED = "REVISION_COMPLETED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"


class AgentRole(StrEnum):
    PROFILE_MANAGER = "PROFILE_MANAGER"
    BEHAVIOR_AGENT = "BEHAVIOR_AGENT"
    INTENT_AGENT = "INTENT_AGENT"
    TREND_AGENT = "TREND_AGENT"
    PROFILE_BUILDER_CRITIC = "PROFILE_BUILDER_CRITIC"


class ArtifactType(StrEnum):
    BEHAVIOR_FACT_REPORT = "BehaviorFactReport"
    INTENT_REPORT = "IntentReport"
    TREND_REPORT = "TrendReport"
    PROFILE_DRAFT = "ProfileDraft"
    PROFILE_AUDIT_REPORT = "ProfileAuditReport"
    USER_PROFILE_VERSION = "UserProfileVersion"


class DemandState(StrEnum):
    DISCOVERING = "DISCOVERING"
    INTERESTED = "INTERESTED"
    INTENT = "INTENT"
    FULFILLED = "FULFILLED"
    COOLING = "COOLING"
    RENEWAL = "RENEWAL"
