spring:
  application:
    name: persona-commerce-server

  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

management:
  endpoint:
    health:
      show-details: always